#!/usr/bin/python3

import amulet
import requests
import unittest
import os


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment()

        self.d.add('puppet-agent')
        self.d.expose('puppet-agent')

        self.d.setup(timeout=900)
        self.d.sentry.wait()

        self.unit = self.d.sentry['puppet-agent'][0]

    def test_config_exists(self):
        if os.path.exists('/opt/puppetlabs/bin/puppet'):
            print('Puppet installed!')
